# Generated by Django 6.1.1 on 2026-09-12 16:05

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BroadsheetSeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_sealed', models.BooleanField(default=False)),
                ('sealed_at', models.DateTimeField(blank=True, null=True)),
                ('submission_notes', models.TextField(blank=True)),
                ('missing_marks_count', models.PositiveIntegerField(default=0)),
                ('class_arm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broadsheet_seals', to='academics.classarm')),
                ('sealed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broadsheet_seals', to=settings.AUTH_USER_MODEL)),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broadsheet_seals', to='academics.academicterm')),
            ],
            options={
                'verbose_name': 'Broadsheet Seal',
                'verbose_name_plural': 'Broadsheet Seals',
                'ordering': ['-term__session__name', 'class_arm'],
                'unique_together': {('class_arm', 'term')},
            },
        ),
        migrations.CreateModel(
            name='SubjectMarksheetSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('SUBMITTED', 'Submitted'), ('MODERATED', 'Moderated')], default='IN_PROGRESS', max_length=16)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('graded_students_count', models.PositiveIntegerField(default=0)),
                ('total_students_count', models.PositiveIntegerField(default=0)),
                ('class_average', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=5)),
                ('submission_comments', models.TextField(blank=True)),
                ('class_arm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marksheet_submissions', to='academics.classarm')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marksheet_submissions', to='academics.subject')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marksheet_submissions', to=settings.AUTH_USER_MODEL)),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marksheet_submissions', to='academics.academicterm')),
            ],
            options={
                'verbose_name': 'Subject Marksheet Submission',
                'verbose_name_plural': 'Subject Marksheet Submissions',
                'ordering': ['-term__session__name', 'class_arm', 'subject'],
                'unique_together': {('class_arm', 'subject', 'term')},
            },
        ),
        migrations.CreateModel(
            name='SubjectScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ca1', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('ca2', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('assignment', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('project', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('exam', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(60)])),
                ('total', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=5)),
                ('grade', models.CharField(blank=True, max_length=2)),
                ('remark', models.CharField(blank=True, max_length=32)),
                ('teacher_remark', models.CharField(blank=True, max_length=255)),
                ('is_locked', models.BooleanField(default=False)),
                ('is_overridden', models.BooleanField(default=False)),
                ('override_reason', models.TextField(blank=True)),
                ('override_ticket_id', models.CharField(blank=True, max_length=64)),
                ('overridden_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('previous_score', models.JSONField(blank=True, null=True)),
                ('class_arm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='academics.classarm')),
                ('overridden_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='score_overrides', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='students.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='academics.subject')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='academics.academicterm')),
            ],
            options={
                'verbose_name': 'Subject Score',
                'verbose_name_plural': 'Subject Scores',
                'ordering': ['student', 'subject'],
                'unique_together': {('student', 'subject', 'term')},
            },
        ),
    ]
