# Generated by Django 6.1.1 on 2026-09-12 17:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamTimetableEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_date', models.DateField()),
                ('time_slot', models.CharField(max_length=64)),
                ('session_type', models.CharField(choices=[('MORNING', 'Morning'), ('AFTERNOON', 'Afternoon')], default='MORNING', max_length=16)),
                ('applicable_classes', models.JSONField(default=list)),
                ('exam_hall', models.CharField(max_length=100)),
                ('special_instructions', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chief_invigilator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chief_invigilated_exams', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_timetable_entries', to='academics.subject')),
            ],
            options={
                'verbose_name': 'Exam Timetable Entry',
                'verbose_name_plural': 'Exam Timetable Entries',
                'ordering': ['exam_date', 'session_type', 'time_slot'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyTimetablePeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], max_length=16)),
                ('period_number', models.PositiveSmallIntegerField()),
                ('time_range', models.CharField(max_length=32)),
                ('room_or_lab', models.CharField(default='Senior Wing', max_length=64)),
                ('is_break', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_arm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_periods', to='academics.classarm')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_periods', to='academics.subject')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taught_periods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Weekly Timetable Period',
                'verbose_name_plural': 'Weekly Timetable Periods',
                'ordering': ['class_arm', 'day', 'period_number'],
                'unique_together': {('class_arm', 'day', 'period_number')},
            },
        ),
    ]
