# Generated by Django 6.1.1 on 2026-09-12 17:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principal_name', models.CharField(default='Dr. Michael Adebayo', max_length=100)),
                ('principal_title', models.CharField(default='Principal & Head of School', max_length=100)),
                ('principal_signature', models.ImageField(blank=True, null=True, upload_to='settings/signatures/')),
                ('watermark_seal', models.ImageField(blank=True, null=True, upload_to='settings/seals/')),
                ('show_watermark_in_print', models.BooleanField(default=True)),
                ('show_watermark_in_preview', models.BooleanField(default=True)),
                ('auto_sign_report_cards', models.BooleanField(default=True)),
                ('school_motto', models.CharField(default='Excellence • Character • Leadership', max_length=255)),
                ('school_address', models.TextField(default='Kilometer 14, Lekki-Epe Expressway, Lagos, Nigeria')),
                ('school_phone', models.CharField(default='+234 802 345 6789', max_length=32)),
                ('school_email', models.EmailField(default='admissions@everest.edu.ng', max_length=254)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'School Settings',
                'verbose_name_plural': 'School Settings',
            },
        ),
        migrations.CreateModel(
            name='AuditLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_role', models.CharField(max_length=32)),
                ('action', models.CharField(max_length=64)),
                ('target_entity', models.CharField(max_length=100)),
                ('details', models.TextField()),
                ('diff', models.JSONField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log Entry',
                'verbose_name_plural': 'Audit Log Entries',
                'ordering': ['-timestamp'],
            },
        ),
    ]
