# Generated by Django 6.1.1 on 2026-09-13 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='active_role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('PRINCIPAL', 'Principal'), ('VICE_PRINCIPAL', 'Vice Principal'), ('VICE_PRINCIPAL_ACADEMICS', 'VP Academics'), ('VICE_PRINCIPAL_ADMIN', 'VP Admin'), ('EXAM_OFFICER', 'Exam Officer'), ('FORM_MASTER', 'Form Master'), ('SUBJECT_TEACHER', 'Subject Teacher'), ('ADMISSIONS_OFFICER', 'Admissions Officer'), ('PARENT', 'Parent'), ('STUDENT', 'Student')], default='SUBJECT_TEACHER', max_length=32),
        ),
    ]
