# Generated by Django 6.1.1 on 2026-09-14 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_active_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='default_pin',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
