# Generated by Django 6.1.1 on 2026-09-12 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('is_current', models.BooleanField(default=False)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Academic Session',
                'verbose_name_plural': 'Academic Sessions',
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='ClassLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('section', models.CharField(choices=[('JUNIOR', 'Junior Secondary'), ('SENIOR', 'Senior Secondary')], max_length=10)),
                ('order', models.PositiveSmallIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Class Level',
                'verbose_name_plural': 'Class Levels',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=16, unique=True)),
                ('category', models.CharField(choices=[('CORE', 'Core'), ('SCIENCE', 'Science'), ('ARTS', 'Arts'), ('COMMERCIAL', 'Commercial'), ('GENERAL', 'General')], max_length=32)),
                ('applicable_to', models.CharField(choices=[('ALL', 'All'), ('JUNIOR', 'Junior Secondary Only'), ('SENIOR', 'Senior Secondary Only')], default='ALL', max_length=16)),
                ('group', models.CharField(choices=[('CORE', 'Core Compulsory'), ('LANGUAGE', 'Language'), ('TRADE', 'Trade / Vocational'), ('GENERAL_ELECTIVE', 'General Elective')], max_length=32)),
                ('is_compulsory_junior', models.BooleanField(default=False)),
                ('is_compulsory_senior_science', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AcademicTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('1st Term', '1st Term'), ('2nd Term', '2nd Term'), ('3rd Term', '3rd Term')], max_length=16)),
                ('resumption_date', models.DateField()),
                ('closing_date', models.DateField()),
                ('next_term_resumption_date', models.DateField()),
                ('is_active', models.BooleanField(default=False)),
                ('is_results_published', models.BooleanField(default=False)),
                ('is_results_approved_by_principal', models.BooleanField(default=False)),
                ('principal_approved_at', models.DateTimeField(blank=True, null=True)),
                ('principal_approved_by', models.CharField(blank=True, max_length=128)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='academics.academicsession')),
            ],
            options={
                'verbose_name': 'Academic Term',
                'verbose_name_plural': 'Academic Terms',
                'ordering': ['session', 'name'],
                'unique_together': {('session', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ClassArm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('full_name', models.CharField(max_length=64)),
                ('form_master', models.ForeignKey(blank=True, limit_choices_to={'active_role': 'FORM_MASTER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homeroom_arms', to=settings.AUTH_USER_MODEL)),
                ('class_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arms', to='academics.classlevel')),
            ],
            options={
                'verbose_name': 'Class Arm',
                'verbose_name_plural': 'Class Arms',
                'ordering': ['class_level__order', 'name'],
                'unique_together': {('class_level', 'name')},
            },
        ),
        migrations.CreateModel(
            name='TeacherAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_arm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_allocations', to='academics.classarm')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_allocations', to='academics.subject')),
                ('teacher', models.ForeignKey(limit_choices_to={'active_role': 'SUBJECT_TEACHER'}, on_delete=django.db.models.deletion.CASCADE, related_name='teaching_allocations', to=settings.AUTH_USER_MODEL)),
                ('term', models.ForeignKey(blank=True, help_text='Leave blank to apply to all terms in the session.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_allocations', to='academics.academicterm')),
            ],
            options={
                'verbose_name': 'Teacher Allocation',
                'verbose_name_plural': 'Teacher Allocations',
                'unique_together': {('class_arm', 'subject', 'term')},
            },
        ),
    ]
