# Generated by Django 6.1.1 on 2026-09-12 15:41

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_number', models.CharField(db_index=True, max_length=32, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=10)),
                ('date_of_birth', models.DateField()),
                ('state_of_origin', models.CharField(max_length=64)),
                ('lga', models.CharField(max_length=64)),
                ('address', models.TextField(blank=True)),
                ('passport_photo', models.ImageField(blank=True, null=True, upload_to='students/passports/')),
                ('house', models.CharField(choices=[('Emerald', 'Emerald'), ('Sapphire', 'Sapphire'), ('Ruby', 'Ruby'), ('Diamond', 'Diamond')], max_length=16)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=8)),
                ('genotype', models.CharField(choices=[('AA', 'AA'), ('AS', 'AS'), ('AC', 'AC'), ('SS', 'SS')], max_length=8)),
                ('parent_name', models.CharField(blank=True, max_length=120)),
                ('parent_phone', models.CharField(blank=True, max_length=25)),
                ('parent_email', models.EmailField(blank=True, max_length=254)),
                ('is_boarder', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('GRADUATED', 'Graduated'), ('TRANSFERRED', 'Transferred')], default='ACTIVE', max_length=16)),
                ('current_class_arm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='academics.classarm')),
                ('parent', models.ForeignKey(blank=True, limit_choices_to={'active_role': 'PARENT'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wards', to=settings.AUTH_USER_MODEL)),
                ('registered_subjects', models.ManyToManyField(blank=True, related_name='enrolled_students', to='academics.subject')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'ordering': ['current_class_arm', 'last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='DroppedSubjectRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('SSS 2', 'SSS 2'), ('SSS 3', 'SSS 3')], max_length=10)),
                ('reason', models.TextField(blank=True)),
                ('dropped_at', models.DateField(auto_now_add=True)),
                ('academic_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject_drops', to='academics.academicsession')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dropped_by_students', to='academics.subject')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dropped_subjects', to='students.student')),
            ],
            options={
                'verbose_name': 'Dropped Subject Record',
                'verbose_name_plural': 'Dropped Subject Records',
                'ordering': ['-dropped_at'],
                'unique_together': {('student', 'subject')},
            },
        ),
        migrations.CreateModel(
            name='DailyAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('LATE', 'Late'), ('EXCUSED', 'Excused')], default='PRESENT', max_length=10)),
                ('class_arm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='academics.classarm')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='students.student')),
            ],
            options={
                'verbose_name': 'Daily Attendance Record',
                'verbose_name_plural': 'Daily Attendance Records',
                'ordering': ['-date'],
                'unique_together': {('student', 'date')},
            },
        ),
        migrations.CreateModel(
            name='AffectivePsychomotor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punctuality', models.PositiveSmallIntegerField(default=4, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('neatness', models.PositiveSmallIntegerField(default=4, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('politeness', models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('attentiveness', models.PositiveSmallIntegerField(default=4, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('honesty', models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('relationship_with_peers', models.PositiveSmallIntegerField(default=4, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('handwriting', models.PositiveSmallIntegerField(default=4, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('sports_and_games', models.PositiveSmallIntegerField(default=4, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('craftsmanship', models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('musical_artistic_skill', models.PositiveSmallIntegerField(default=4, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('form_master_remark', models.TextField(blank=True)),
                ('principal_remark', models.TextField(blank=True)),
                ('days_present', models.PositiveIntegerField(default=0)),
                ('days_absent', models.PositiveIntegerField(default=0)),
                ('total_school_days', models.PositiveIntegerField(default=65)),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='psychomotor_records', to='academics.academicterm')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='psychomotor_records', to='students.student')),
            ],
            options={
                'verbose_name': 'Affective & Psychomotor Record',
                'verbose_name_plural': 'Affective & Psychomotor Records',
                'unique_together': {('student', 'term')},
            },
        ),
    ]
