# Generated by Django 6.1.1 on 2026-09-12 17:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CampusExeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exeat_type', models.CharField(choices=[('MEDICAL', 'Medical'), ('WEEKEND_HOME', 'Weekend Home'), ('COMPASSIONATE', 'Compassionate'), ('DAY_EARLY_DEPARTURE', 'Day Early Departure')], max_length=32)),
                ('departure_date', models.DateTimeField()),
                ('expected_return_date', models.DateTimeField()),
                ('actual_return_date', models.DateTimeField(blank=True, null=True)),
                ('reason', models.TextField()),
                ('destination', models.CharField(max_length=255)),
                ('authorized_guardian', models.CharField(max_length=100)),
                ('guardian_phone', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('ACTIVE_OFF_CAMPUS', 'Active Off Campus'), ('RETURNED', 'Returned'), ('OVERDUE', 'Overdue'), ('REJECTED', 'Rejected')], default='PENDING', max_length=32)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_exeats', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campus_exeats', to='students.student')),
            ],
            options={
                'verbose_name': 'Campus Exeat',
                'verbose_name_plural': 'Campus Exeats',
                'ordering': ['-departure_date', '-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='DisciplinaryIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_type', models.CharField(choices=[('UNIFORM_DRESS_CODE', 'Uniform / Dress Code'), ('TARDINESS_TRUANCY', 'Tardiness / Truancy'), ('BULLYING_HARASSMENT', 'Bullying / Harassment'), ('DISRUPTIVE_BEHAVIOR', 'Disruptive Behavior'), ('ACADEMIC_DISHONESTY', 'Academic Dishonesty'), ('CONTRABAND_POSSESSION', 'Contraband Possession'), ('VANDALISM', 'Vandalism')], max_length=32)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=16)),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('action_taken', models.CharField(choices=[('VERBAL_WARNING', 'Verbal Warning'), ('WRITTEN_REPRIMAND', 'Written Reprimand'), ('CAMPUS_DETENTION', 'Campus Detention'), ('COMMUNITY_SERVICE', 'Community Service'), ('INTERNAL_SUSPENSION', 'Internal Suspension'), ('PARENTAL_SUMMONS', 'Parental Summons')], max_length=32)),
                ('demerit_points', models.PositiveIntegerField(default=5)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('RESOLVED', 'Resolved'), ('ESCALATED_TO_PRINCIPAL', 'Escalated to Principal')], default='OPEN', max_length=32)),
                ('resolution_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_disciplinary_incidents', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplinary_incidents', to='students.student')),
            ],
            options={
                'verbose_name': 'Disciplinary Incident',
                'verbose_name_plural': 'Disciplinary Incidents',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
